language: java

jdk:
  - oraclejdk8

# Para que use una versión de Java 1.8 que tenga Alert y AlertType
# Por defecto la versión de Java en Travis es la 1.8.0_31
addons:
  apt:
    packages:
      - oracle-java8-installer
